clean:
	rm -rf ./data
create:
	mkdir -p data/t1/t1_1
	mkdir -p data/t2/t2_1
	mkdir -p data/t2/t2_2

	echo "I am is t1_1" > data/t1/t1_1/t1_1
	echo "I am is t2.txt" > data/t2/t2.txt
	echo "I am is t2_1" > data/t2/t2_1/t2_1.txt